PMS/PMS.WebUI/Areas/ManagementPanel/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PMS.Entities.Models;

namespace PMS.WebUI.Areas.ManagementPanel.Controllers
{
    [Area("ManagementPanel")]
    public class EmployeesController : Controller
    {
        private readonly PmsContext _context = new PmsContext();

        // GET: ManagementPanel/Employees
        public async Task<IActionResult> Index()
        {
            var pmsContext = _context.Employees.Include(e => e.Store);
            return View(await pmsContext.ToListAsync());
        }

        // GET: ManagementPanel/Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Store)
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: ManagementPanel/Employees/Create
        public IActionResult Create()
        {
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "Address");
            return View();
        }

        // POST: ManagementPanel/Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "Address", employee.StoreId);
            return View(employee);
        }

        // GET: ManagementPanel/Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "Address", employee.StoreId);
            return View(employee);
        }

        // POST: ManagementPanel/Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Employee employee)
        {
            if (ModelState.IsValid)
            {
                try
                {
                   
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StoreId"] = new SelectList(_context.Stores, "StoreId", "Address", employee.StoreId);
            return View(employee);
        }
    }
}

PMS/PMS.WebUI/Areas/ManagementPanel/Controllers/MainPagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using PMS.Entities.Models;
using PMS.WebUI.Areas.ManagementPanel.Helpers;

namespace PMS.WebUI.Areas.ManagementPanel.Controllers
{
    [Area("ManagementPanel")]
    public class MainPagesController : Controller
    {
        private readonly PmsContext _context = new PmsContext();

        private readonly IWebHostEnvironment _hostEnvironment;

        public MainPagesController(IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
        }
        // GET: ManagementPanel/MainPages
        public async Task<IActionResult> Index()
        {
              return View(await _context.MainPages.ToListAsync());
        }

        // GET: ManagementPanel/MainPages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ManagementPanel/MainPages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MainPage mainPage, IFormFile img)
        {
            if (ModelState.IsValid)
            {
                if (img != null)
                {
                    mainPage.ImageUrl = await İmageUpload.UploadImageAsync(_hostEnvironment, img);
                }
                _context.Add(mainPage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mainPage);
        }

        // GET: ManagementPanel/MainPages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MainPages == null)
            {
                return NotFound();
            }

            var mainPage = await _context.MainPages.FindAsync(id);
            if (mainPage == null)
            {
                return NotFound();
            }
            return View(mainPage);
        }

        // POST: ManagementPanel/MainPages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MainPage mainPage, IFormFile img)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MainPage editmainpage = await _context.MainPages.FirstOrDefaultAsync(r => r.MainPageId == mainPage.MainPageId);
                    if (img != null)
                    {
                        editmainpage.ImageUrl = await İmageUpload.UploadImageAsync(_hostEnvironment, img);
                    }

                    editmainpage.Title = mainPage.Title;
                    editmainpage.Notice = mainPage.Notice;
                    editmainpage.Description = mainPage.Description;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                }
                return RedirectToAction(nameof(Index));
            }
            return View(mainPage);
        }

    }
}

PMS/PMS.WebUI/Areas/ManagementPanel/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PMS.Entities.Models;

namespace PMS.WebUI.Areas.ManagementPanel.Controllers
{
    [Area("ManagementPanel")]
    public class StoresController : Controller
    {
        private readonly PmsContext _context = new PmsContext();

        // GET: ManagementPanel/Stores
        public async Task<IActionResult> Index()
        {
            var pmsContext = _context.Stores.Include(s => s.Manager);
            return View(await pmsContext.ToListAsync());
        }

        // GET: ManagementPanel/Stores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Stores == null)
            {
                return NotFound();
            }

            var store = await _context.Stores
                .Include(s => s.Manager)
                .FirstOrDefaultAsync(m => m.StoreId == id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // GET: ManagementPanel/Stores/Create
        public IActionResult Create()
        {
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "Email");
            return View();
        }

        // POST: ManagementPanel/Stores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Store store)
        {
            if (ModelState.IsValid)
            {
                _context.Add(store);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "Email", store.ManagerId);
            return View(store);
        }

        // GET: ManagementPanel/Stores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Stores == null)
            {
                return NotFound();
            }

            var store = await _context.Stores.FindAsync(id);
            if (store == null)
            {
                return NotFound();
            }
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "Email", store.ManagerId);
            return View(store);
        }

        // POST: ManagementPanel/Stores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Store store)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Store editStores = await _context.Stores.FindAsync(store.StoreId);

                    editStores.Name = store.Name;
                    editStores.Email = store.Email;
                    editStores.Phone = store.Phone;
                    editStores.Address = store.Address;
                    editStores.Manager.Email = store.Manager.Email;

                    _context.Update(store);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                   
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManagerId"] = new SelectList(_context.Managers, "ManagerId", "Email", store.ManagerId);
            return View(store);
        }
    }
}

PMS/PMS.WebUI/Areas/ManagementPanel/Views/Shared/_Footer.cshtml
<!--footer -->
<div class="footer">
	<p class="mb-0">
		Syndash 2020 | Developed By : <a href="https://themeforest.net/user/codervent" target="_blank">codervent</a>
	</p>
</div>
<!-- end footer -->

PMS/PMS.WebUI/Areas/ManagementPanel/Views/Shared/_Head.cshtml
<!-- Required meta tags -->
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<title>Syndash - Bootstrap4 Admin Template</title>
<!--favicon-->
<link rel="icon" href="~/Areas/images/favicon-32x32.png" type="image/png" />
<!-- Vector CSS -->
<link href="~/Areas/plugins/vectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
<!--plugins-->
<link href="~/Areas/plugins/simplebar/css/simplebar.css" rel="stylesheet" />
<link href="~/Areas/plugins/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet" />
<link href="~/Areas/plugins/metismenu/css/metisMenu.min.css" rel="stylesheet" />
<!-- loader-->
<link href="~/Areas/css/pace.min.css" rel="stylesheet" />
<script src="~/Areas/js/pace.min.js"></script>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="~/Areas/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;600&amp;family=Roboto&amp;display=swap" />
<!-- Icons CSS -->
<link rel="stylesheet" href="~/Areas/css/icons.css" />
<!-- App CSS -->
<link rel="stylesheet" href="~/Areas/css/app.css" />
<link rel="stylesheet" href="~/Areas/css/dark-sidebar.css" />
<link rel="stylesheet" href="~/Areas/css/dark-theme.css" />

PMS/PMS.WebUI/Areas/ManagementPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from codervent.com/syndash/demo/vertical/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 06 Mar 2021 13:20:51 GMT -->
<head>
	@Html.Partial("_Head")
</head>

<body>
	<div class="wrapper">
		@Html.Partial("_Sidebar")

		@Html.Partial("_Header")

		<div class="page-wrapper">
			<div class="page-content-wrapper">
				<div class="page-content">
					@RenderBody()
				</div>
			</div>
		</div>
		
		<div class="overlay toggle-btn-mobile"></div>
	    <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
		
		@Html.Partial("_Footer")
	</div>
	@Html.Partial("_Scripts")
	
</body>


<!-- Mirrored from codervent.com/syndash/demo/vertical/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 06 Mar 2021 13:20:53 GMT -->
</html>

PMS/PMS.WebUI/Areas/ManagementPanel/Views/Shared/_Scripts.cshtml
<!-- JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="~/Areas/js/jquery.min.js"></script>
	<script src="~/Areas/js/popper.min.js"></script>
	<script src="~/Areas/js/bootstrap.min.js"></script>
	<!--plugins-->
	<script src="~/Areas/plugins/simplebar/js/simplebar.min.js"></script>
	<script src="~/Areas/plugins/metismenu/js/metisMenu.min.js"></script>
	<script src="~/Areas/plugins/perfect-scrollbar/js/perfect-scrollbar.js"></script>
	<!-- Vector map JavaScript -->
	<script src="~/Areas/plugins/vectormap/jquery-jvectormap-2.0.2.min.js"></script>
	<script src="~/Areas/plugins/vectormap/jquery-jvectormap-world-mill-en.js"></script>
	<script src="~/Areas/plugins/vectormap/jquery-jvectormap-in-mill.js"></script>
	<script src="~/Areas/plugins/vectormap/jquery-jvectormap-us-aea-en.js"></script>
	<script src="~/Areas/plugins/vectormap/jquery-jvectormap-uk-mill-en.js"></script>
	<script src="~/Areas/plugins/vectormap/jquery-jvectormap-au-mill.js"></script>
	<script src="~/Areas/plugins/apexcharts-bundle/js/apexcharts.min.js"></script>
	<script src="~/Areas/js/index.js"></script>
	<!-- App JS -->
	<script src="~/Areas/js/app.js"></script>
	<script>
		new PerfectScrollbar('.dashboard-social-list');
		new PerfectScrollbar('.dashboard-top-countries');
    </script>

PMS/PMS.WebUI/Areas/ManagementPanel/Views/Shared/_Sidebar.cshtml
<!--sidebar-wrapper-->
<div class="sidebar-wrapper" data-simplebar="true">
	<div class="sidebar-header">
		<div class="">
			<img src="~/Areas/images/logo-icon.png" class="logo-icon-2" alt="" />
		</div>
		<div>
			<h4 class="logo-text">Syndash</h4>
		</div>
		<a href="javascript:;" class="toggle-btn ml-auto">
			<i class="bx bx-menu"></i>
		</a>
	</div>
	<!--navigation-->
	<ul class="metismenu" id="menu">
		<li>
			<a href="javascript:;" class="has-arrow">
				<div class="parent-icon icon-color-1">
					<i class="bx bx-home-alt"></i>
				</div>
				<div class="menu-title">Dashboard</div>
			</a>
		</li>
		<li>
			<a href="@Url.Action("Index", "MainPages")">
				<div class="parent-icon icon-color-1">
					<i class="bx bx-home-alt"></i>
				</div>
				<div class="menu-title">Ana Sayfa</div>
			</a>
		</li>
		<li>
			<a href="@Url.Action("Index", "Stores")">
				<div class="parent-icon icon-color-1">
					<i class="bx bx-home-alt"></i>
				</div>
				<div class="menu-title">Mağaza</div>
			</a>
		</li>
		<li>
			<a href="@Url.Action("Index", "Employees")">
				<div class="parent-icon icon-color-1">
					<i class="bx bx-home-alt"></i>
				</div>
				<div class="menu-title">Çalışanlar</div>
			</a>
		</li>
		
	<!--end navigation-->
</div>
<!--end sidebar-wrapper-->